# Generated by Django 2.0.3 on 2019-12-13 10:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter blog title', max_length=200)),
                ('description', models.TextField(help_text='Give blog description')),
                ('blog_image', models.ImageField(upload_to='uploads/')),
                ('publish_date', models.DateField(default=datetime.datetime(2019, 12, 13, 10, 5, 12, 547766, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter blog category name', max_length=200)),
                ('category_image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
