# Generated by Django 2.0.3 on 2019-12-13 10:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(help_text='Select a blog category', to='catalog.Category'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 13, 10, 6, 49, 699229, tzinfo=utc)),
        ),
    ]
