# Generated by Django 2.0.3 on 2019-12-13 10:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20191213_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 13, 10, 16, 34, 676246, tzinfo=utc)),
        ),
    ]
