# Generated by Django 2.0.3 on 2019-12-18 05:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20191217_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment_date',
        ),
        migrations.AlterField(
            model_name='blog',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 18, 5, 25, 18, 296200, tzinfo=utc)),
        ),
    ]
