# Generated by Django 2.0.3 on 2019-12-20 10:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20191220_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 20, 10, 41, 46, 824236, tzinfo=utc)),
        ),
    ]
